name: rhel7-ml-xopt
channels:
  - conda-forge
dependencies:
  - python=3.9
  - deap
  - numpy
  - pydantic
  - pyyaml
  - pandas # requires scipy
  - pyepics
  - ipywidgets
  - tqdm
# parallel
  - mpi4py
  - dask
# Developer
  - pytest
  - jupyterlab>=3 
  - matplotlib
  - pygments
  - numdifftools
  - scipy
  - pip
  - pip:
    - git+https://github.com/ChristopherMayes/Xopt.git@rewrite
    - git+https://github.com/cornellius-gp/gpytorch.git
    - git+https://github.com/pytorch/botorch.git
    - git+https://github.com/slaclab/PyEmittance.git
