name: Create conda environment with docker 

on:
  push:
    branches:
      - main

jobs:
  build:
    env:
      ENVIRONMENT_NAME: rhel7-ml-xopt
      TEST_FILE: test.sh
    runs-on: ubuntu-latest
    name: Build environment
    steps:
      - name: Build environment
        uses: slaclab/lcls-rhel7-conda-pack@v0.0
